/** @format */

const API_ACCEPT_HEADER = 'Accept';
const API_CONTENT_TYPE_HEADER = 'Content-Type';
const API_JSON_CONTENT_TYPE = 'application/json';

const ASSETS_QUERY_KEY = 'assets';
const ASSETS_LIST_QUERY_KEY = 'list';
const ASSETS_API_PATH = '/assets';

const HTTP_ERROR_MESSAGE_PREFIX = 'Erro HTTP';
const VITE_API_URL_ENV_NAME = 'VITE_API_URL';

export {
	API_ACCEPT_HEADER,
	API_CONTENT_TYPE_HEADER,
	API_JSON_CONTENT_TYPE,
	ASSETS_LIST_QUERY_KEY,
	ASSETS_API_PATH,
	ASSETS_QUERY_KEY,
	HTTP_ERROR_MESSAGE_PREFIX,
	VITE_API_URL_ENV_NAME,
};
