/** @format */

const PAGE_SIZE_OPTIONS = [10, 20, 50] as const;
const DEFAULT_PAGE_INDEX = 0;
const DEFAULT_PAGE_SIZE = PAGE_SIZE_OPTIONS[0];

export {
	DEFAULT_PAGE_INDEX,
	DEFAULT_PAGE_SIZE,
	PAGE_SIZE_OPTIONS,
};
